version: '3.8'
services:

  redis:
    image: redis:alpine
    container_name: redis

  db:
    container_name: postgres_db
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=coin
  web:
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py wait_for_db &&
             python3 manage.py runserver 0.0.0.0:8080"
    depends_on:
      - db
    links:
      - db
      - redis

  celery:
    build: .
    command: celery -A coinmena worker -l info
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - redis
      - web
    links:
      - db
      - redis
  celery-beat:
    restart: always
    build: .
    command: celery -A coinmena beat -l info
    volumes:
      - .:/usr/src/app/
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
      - web

volumes:
  pgdata: