# Generated by Django 3.2.8 on 2021-10-17 15:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=5)),
                ('currency', models.CharField(max_length=50)),
                ('timezone', models.CharField(max_length=3)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
