# Generated by Django 3.2.8 on 2021-10-17 16:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='code',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='information',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='timezone',
        ),
        migrations.AddField(
            model_name='quotes',
            name='meta_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
